sendjpmail : rewritten almost of all, and a lot of improvements

diff --git a/base64 b/base64
--- a/base64
+++ b/base64
@@ -12,12 +12,13 @@
 #                         Not use the "built-in" base64 command and
 #                         always do base64 by myself but it is inferior
 #                         to the built-in in performance
+#        "-d" ........... Run as a Base64 decoder.
 #        "-w <COLS>" .... When encoding, wrap encoded lines after COLS
 #                         character (default 76). 0 means preventing
 #                         from wrapping.
 #        "-i" ........... When decoding, ignore non-alphabet characters.
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/04
+# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/07
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -30,7 +31,7 @@ print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [--by-myself] [-w <COLS>] <file>
 	          ${0##*/} [--by-myself] -d [-i] <file>
-	Version : Wed Feb  4 04:10:07 JST 2015
+	Version : Sat Feb  7 00:24:34 JST 2015
 	        : (POSIX.1 Bourne Shell/POSIX.1 commands)
 	        :   * Although the bult-in base64 command or GNU AWK produces
 	        :     better performance than the POSIX command set
@@ -43,29 +44,23 @@ __USAGE
 # --- which command also works on Just a POSIX environment -----------
 which which >/dev/null 2>&1 || {
   which () {
-    case "$1" in
-       /*) ls   "$1" 2>/dev/null; return $?;;
-      */*) ls "./$1" 2>/dev/null; return $?;;
-    esac
     (
-      echo "$PATH" | tr ':' '\n' | while read dir; do
-        case "$dir" in '') break;; esac
-        ls "${dir%/}/$1" 2>/dev/null && exit 1 || continue
-      done
-      exit $((1-$?))
+      ans=$(LANG=C LC_ALL=C type "$1") || exit $?
+      case "$1"   in */*) printf '%s\n' "$1"        ; exit;; esac
+      case "$ans" in */*) printf '%s\n' "/${ans#*/}"; exit;; esac
+      printf '%s\n' "$1"
     )
-    return $?
   }
 }
 
-# --- miac setting #1 ------------------------------------------------
+# --- misc setting #1 ------------------------------------------------
 PATH='/usr/bin:/bin:/usr/local/bin'
 set -u
 
 # --- exec the "bult-in" base64 command if exists --------------------
 case "${1:-}" in
-  --by-myself) shift                                                         ;;
-  *)           which base64 >/dev/null 2>&1 && { exec base64 "$@"; exit 1; } ;;
+  --by-myself) shift                                                        ;;
+  *)           type base64 >/dev/null 2>&1 && { exec base64 "$@"; exit 1; } ;;
 esac
 
 # --- check whether this host has a "binarable" AWK command or not ---
@@ -78,7 +73,7 @@ while :; do
   binarable_awk=0; break
 done
 
-# --- miac setting #2 ------------------------------------------------
+# --- misc setting #2 ------------------------------------------------
 PATH='/usr/bin:/bin'
 export LC_ALL=C
 export LANG=C
@@ -97,12 +92,12 @@ while :; do
     '') case "$1" in
           -)        case $# in 1) break;; esac
                     ;;
-          -[diw]*)  s=$(echo "_${1#-}"                                     |
+          -[diw]*)  s=$(printf '%s\n' "${1#-}"                             |
                         awk '{d = "_"; i = "_"; w = "_"; err=0;            #
                               s = $0;                                      #
                               sub(/w[0-9]+$/, "w", s);                     #
                               l = length(s);                               #
-                              for (n=2;n<=l;n++) {                         #
+                              for (n=1;n<=l;n++) {                         #
                                 c = substr(s, n, 1);                       #
                                 if      ( c=="d"         ) { d   = "d"; }  #
                                 else if ( c=="i"         ) { i   = "i"; }  #
@@ -151,8 +146,8 @@ while :; do
         ;;
   esac
   case "$optmode" in
-    w) echo "_$s" | grep -q '^_[0-9]\{1,\}$' || {
-         echo "${0##*/}: Invalid value of -w,--wrap option" 1>&2
+    w) printf '%s\n' "$s" | grep -q '^[0-9]\{1,\}$' || {
+         printf '%s\n' "${0##*/}: Invalid value of -w,--wrap option" 1>&2
          exit 1
        }
        width=$s
diff --git a/gzpipe b/gzpipe
--- a/gzpipe
+++ b/gzpipe
@@ -47,7 +47,7 @@
 #   That means, you can join various filters to fd=2 (stderr). Although
 #   it is very tricky. ;-)
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/03
+# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/07
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -64,27 +64,9 @@ DEFAULT_TIMEOUT=600
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [-t timeout] <named_pipe_to_use> [output_file]
-	Version : Tue Feb  3 16:36:39 JST 2015
+	Version : Sat Feb  7 00:32:39 JST 2015
 __USAGE
   exit 1
-}
-
-# --- which command also works on Just a POSIX environment -----------
-which which >/dev/null 2>&1 || {
-  which () {
-    case "$1" in
-       /*) ls   "$1" 2>/dev/null; return $?;;
-      */*) ls "./$1" 2>/dev/null; return $?;;
-    esac
-    (
-      echo "$PATH" | tr ':' '\n' | while read dir; do
-        case "$dir" in '') break;; esac
-        ls "${dir%/}/$1" 2>/dev/null && exit 1 || continue
-      done
-      exit $((1-$?))
-    )
-    return $?
-  }
 }
 
 
@@ -110,8 +92,8 @@ done
 case $check in 'p')
 
   # --- make sure that gzip command exists ---------------------------
-  which gzip >/dev/null 2>&1 || {
-    echo "${0##*/}: gzip command is not found" 1>&2
+  type gzip >/dev/null 2>&1 || {
+    printf '%s\n' "${0##*/}: gzip command is not found" 1>&2
     exit 1
   }
 
@@ -139,6 +121,8 @@ case $check in 'p')
   outfile=''
   case $# in 2) case "$2" in '') :;; *) outfile=$2;; esac;; esac
   case "$pipe" in                  "$outfile") print_usage_and_exit;; esac
+  case "$pipe"    in -*) pipe="./$pipe"      ;; esac
+  case "$outfile" in -*) outfile="./$outfile";; esac
 
   # --- enable the exit trap -----------------------------------------
   trap 'exit_trap' EXIT HUP INT QUIT PIPE ALRM TERM
@@ -154,7 +138,7 @@ case $check in 'p')
        mkfifo -m 600 "$pipe"
        case $? in
          0)  :                                                          ;;
-         *)  echo "${0##*/}: Can't make the named pipe" 1>&2
+         *)  printf '%s\n' "${0##*/}: Can't make the named pipe" 1>&2
              exit_trap 2                                                ;;
        esac
        namedpipe_to_del_by_myself=$pipe
@@ -162,11 +146,11 @@ case $check in 'p')
     0[^0-9]*)                         # $?==0 && $check!=''
        case "$check" in
          p*) :                                                          ;;
-         *)  echo "${0##*/}: \"$pipe\" exists as another attribute" 1>&2
-             exit_trap 3                                                ;;
+         *) printf '%s\n' "${0##*/}: \"$pipe\" exists as another attribute" 1>&2
+            exit_trap 3                                                 ;;
        esac
        ;;
-    *) echo "${0##*/}: An error occured at executing ls command" 1>&2
+    *) printf '%s\n' "${0##*/}: An error occured at executing ls command" 1>&2
        exit_trap 4
        ;;
   esac
@@ -219,13 +203,13 @@ case $check in 'p')
   file=$2
   case "$3" in [01]) :;; *) echo '*** Invalid argument #3' 1>&3; exit 13;; esac
   del_the_pipe=$3
-  echo "_$4" | grep -q '^_[0-9]\+$' ||
+  printf '%s\n' "$4" | grep -q '^[0-9]\+$' ||
                           { echo '*** Invalid argument #4' 1>&3; exit 14; }
   ppid=$4
-  echo "_$5" | grep -q '^_[0-9]\+$' ||
+  printf '%s\n' "$5" | grep -q '^[0-9]\+$' ||
                           { echo '*** Invalid argument #5' 1>&3; exit 15; }
   cpid=$5
-  echo "_$6" | grep -q '^_[0-9]\+$' ||
+  printf '%s\n' "$6" | grep -q '^[0-9]\+$' ||
                           { echo '*** Invalid argument #6' 1>&3; exit 16; }
   timeout=$6
 
@@ -256,7 +240,7 @@ case $check in 'p')
   kill -s TERM "$ppid"
 
   # --- make a temporary file ----------------------------------------
-  if which mktemp >/dev/null 2>&1; then
+  if type mktemp >/dev/null 2>&1; then
     gz_file=$(mktemp -t "${0##*/}.XXXXXXXX")
   else
     gz_file="/tmp/${0##*/}.$$"
@@ -264,8 +248,8 @@ case $check in 'p')
     chmod 600 "$gz_file"
   fi
   case $? in
-    0) :                                                        ;;
-    *) echo "${0##*/}: Can't make a tempfile" 1>&3; exit_trap 18;;
+    0) :                                                                 ;;
+    *) printf '%s\n' "${0##*/}: Can't make a tempfile" 1>&3; exit_trap 18;;
   esac
 
   # --- set my life time ---------------------------------------------
diff --git a/hira2kata b/hira2kata
--- a/hira2kata
+++ b/hira2kata
@@ -12,7 +12,7 @@ print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [+<n>h] <f1> <f2> ... <file>
 	        : ${0##*/} -d <string>
-	Version : Sun Jan 18 22:40:26 JST 2015
+	Version : Sat Feb  7 00:37:00 JST 2015
 	        : (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 __USAGE
   exit 1
@@ -43,7 +43,7 @@ for arg in "$@"; do
     directmode=1
     continue
   elif [ \( $opt_part -ne 0 \) -a \( "_$arg" != "_${arg#+}" \) ]; then
-    s=$(echo "_$arg" | sed 's/^_+\([0-9]*\)h$/\1/')
+    s=$(printf '%s\n' "$arg" | sed 's/^+\([0-9]*\)h$/\1/')
     case "$s" in "$arg") print_usage_and_exit;; esac
     case "$s" in     '') hopt=1; continue    ;; esac
     hopt=$(expr $s + 0)
@@ -65,10 +65,10 @@ for arg in "$@"; do
   # check both
   j=0
   for s in $arg1 $arg2; do
-    if echo "_$s" | grep -q '^_[0-9]\{1,\}$'; then
+    if printf '%s\n' "$s" | grep -q '^[0-9]\{1,\}$'; then
       j=$((j+1))
       case "$s" in 0) all_fields=1;; esac
-    elif echo "_$s" | grep -Eq '^_(NF|NF-[0-9]+)$'; then
+    elif printf '%s\n' "$s" | grep -Eq '^(NF|NF-[0-9]+)$'; then
       j=$((j+1))
     fi
   done
@@ -99,7 +99,7 @@ case $directmode in
      then
        print_usage_and_exit
      elif [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-       echo "${0##*/}: Cannot open the file" 1>&2
+       printf '%s\n' "${0##*/}: Cannot open the file" 1>&2
        exit 1
      fi
      ;;
@@ -107,6 +107,7 @@ case $directmode in
      file=''
      ;;
 esac
+case "$file" in -) :;; -*) file="./$file";; esac
 
 # make the part of the awk code
 case $all_fields in
diff --git a/is_furigana b/is_furigana
--- a/is_furigana
+++ b/is_furigana
@@ -15,7 +15,7 @@
 #
 # Return : $?に判定結果
 #
-# Written by Rich Mikan(richmikan@richlab.org) at 2015/01/18
+# Written by Rich Mikan(richmikan@richlab.org) at 2015/02/07
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -27,7 +27,7 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} <file>
-	Version : Sun Jan 18 23:08:01 JST 2015
+	Version : Sat Feb  7 00:44:28 JST 2015
 __USAGE
   exit 1
 }
@@ -43,9 +43,10 @@ else
   print_usage_and_exit
 fi
 if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the file" 1>&2
+  printf '%s\n' "${0##*/}: Cannot open the file" 1>&2
   exit 1
 fi
+case "$file" in -) :;; -*) file="./$file";; esac
 
 # main
 exec env - awk '
diff --git a/mkstemp b/mkstemp
--- a/mkstemp
+++ b/mkstemp
@@ -8,7 +8,7 @@
 #
 # * "mktemp(1) options" depend on mktemp(1) on the host
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/01/26
+# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/07
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -21,7 +21,7 @@ print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [mktemp(1)options] <template>
 	          "mktemp(1) options" depend on mktemp(1) on the host.
-	Version : Mon Jan 26 15:22:35 JST 2015
+	Version : Sat Feb  7 01:11:12 JST 2015
 __USAGE
   exit 1
 }
@@ -35,7 +35,7 @@ PATH='/usr/bin:/bin'
 
 
 # --- use the built-in mktemp command if not need to do by myself ----
-which mktemp >/dev/null 2>&1
+type mktemp >/dev/null 2>&1
 case $? in
   0) [ -f /etc/issue ] && grep -q '^CentOS.* 5\.[0-9]' /etc/issue
      case $? in
@@ -85,10 +85,10 @@ optmode=''
 while :; do
   case "$optmode" in
     '') case "$1" in
-          -[duqtp]*)   s=$(echo "_${1#-}"                                |
+          -[duqtp]*)   s=$(printf '%s\n' "${1#-}"                        |
                            awk '{d = "_"; u = "_"; q = "_";              #
                                  t = "_"; p = "_"; err = 0;              #
-                                 for (i=2;i<=length($0);i++) {           #
+                                 for (i=1;i<=length($0);i++) {           #
                                    s = substr($0,i,1);                   #
                                    if      (s == "d") { d   = "d"; }     #
                                    else if (s == "u") { u   = "u"; }     #
@@ -121,13 +121,13 @@ while :; do
   esac
   case "$optmode" in
     p) [ -d "$s" ] || {
-         echo "${0##*/}: Invalid path by -p,--tmpdir option" 1>&2
+         printf '%s\n' "${0##*/}: Invalid path by -p,--tmpdir option" 1>&2
          exit 1
        }
        Dir_tmp=${s%/}; [ -n "$Dir_tmp" ] || Dir_tmp='/.'
        optmode=''; shift; continue        ;;
     s) { printf '%s' "$s" | grep -q '/'; } && {
-         echo "${0##*/}: Invalid suffix option" 1>&2
+         printf '%s\n' "${0##*/}: Invalid suffix option" 1>&2
          exit 1
        }
        opts=$s
@@ -218,6 +218,9 @@ for arg in "$@"; do
     Path_target=$(printf '%s' "$Path_target" |
                   sed 's!//!/!g'             |
                   sed 's!/./!/!g'            )
+    #
+    # for security
+    case "$Path_target" in -*) Path_target="./$Path_target";; esac
 
     # --- Making the file --------------------------------------------
     case $optd in
@@ -238,12 +241,17 @@ for arg in "$@"; do
 
   # --- print error message when failed to make a file ---------------
   case "${optq}${n}" in
-    '0-1') echo "${0##*/}: failed on $Path_target" 1>&2; err=1; continue;;
-    '1-1')                                               err=1; continue;;
+    '0-1') printf '%s\n' "${0##*/}: failed on $Path_target" 1>&2
+           err=1
+           continue
+           ;;
+    '1-1') err=1
+           continue
+           ;;
   esac
 
   # --- print the path of the file -----------------------------------
-  echo "$Path_target"
+  printf '%s\n' "$Path_target"
 
   # --- remove the file if -u,--dry-run option is set ----------------
   case $optu in 1) rm -rf "$Path_target";; esac
diff --git a/mktemp b/mktemp
--- a/mktemp
+++ b/mktemp
@@ -19,7 +19,7 @@
 #                            in front of the filepath
 #        "--suffix=<suff>" . Add the suffix behind the filename
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/02
+# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/07
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -32,31 +32,13 @@ print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [--by-myself] [options] [template [...]]
 	        : "-d" "-p [DIR]" "-q" "-u" "-t" "--suffix=<suff>"
-	Version : Mon Feb  2 21:53:44 JST 2015
+	Version : Sat Feb  7 01:21:44 JST 2015
 __USAGE
   exit 1
 }
 
 
 # ===== PREPARATION ==================================================
-
-# --- which command also works on Just a POSIX environment -----------
-which which >/dev/null 2>&1 || {
-  which () {
-    case "$1" in
-       /*) ls   "$1" 2>/dev/null; return $?;;
-      */*) ls "./$1" 2>/dev/null; return $?;;
-    esac
-    (
-      echo "$PATH" | tr ':' '\n' | while read dir; do
-        case "$dir" in '') break;; esac
-        ls "${dir%/}/$1" 2>/dev/null && exit 1 || continue
-      done
-      exit $((1-$?))
-    )
-    return $?
-  }
-}
 
 # --- set the command path -------------------------------------------
 PATH='/usr/bin:/bin'
@@ -77,8 +59,8 @@ LF=$(printf '\\\n_');LF=${LF%_}
 
 # --- exec the mktemp command if exists ------------------------------
 case "${1:-}" in
-  --by-myself) shift                                                         ;;
-  *)           which mktemp >/dev/null 2>&1 && { exec mktemp "$@"; exit 1; } ;;
+  --by-myself) shift                                                        ;;
+  *)           type mktemp >/dev/null 2>&1 && { exec mktemp "$@"; exit 1; } ;;
 esac
 
 
@@ -94,10 +76,10 @@ while :; do
   case $# in 0) break;; esac
   case "$optmode" in
     '') case "$1" in
-          -[duqtp]*)   s=$(echo "_${1#-}"                                |
+          -[duqtp]*)   s=$(printf '%s\n' "${1#-}"                        |
                            awk '{d = "_"; u = "_"; q = "_";              #
                                  t = "_"; p = "_"; err = 0;              #
-                                 for (i=2;i<=length($0);i++) {           #
+                                 for (i=1;i<=length($0);i++) {           #
                                    s = substr($0,i,1);                   #
                                    if      (s == "d") { d   = "d"; }     #
                                    else if (s == "u") { u   = "u"; }     #
@@ -130,13 +112,13 @@ while :; do
   esac
   case "$optmode" in
     p) [ -d "$s" ] || {
-         echo "${0##*/}: Invalid path by -p,--tmpdir option" 1>&2
+         printf '%s\n' "${0##*/}: Invalid path by -p,--tmpdir option" 1>&2
          exit 1
        }
        Dir_tmp=${s%/}; [ -n "$Dir_tmp" ] || Dir_tmp='/.'
        optmode=''; shift; continue        ;;
     s) { printf '%s' "$s" | grep -q '/'; } && {
-         echo "${0##*/}: Invalid suffix option" 1>&2
+         printf '%s\n' "${0##*/}: Invalid suffix option" 1>&2
          exit 1
        }
        opts=$s
@@ -227,6 +209,9 @@ for arg in "$@"; do
     Path_target=$(printf '%s' "$Path_target" |
                   sed 's!//!/!g'             |
                   sed 's!/./!/!g'            )
+    #
+    # for security
+    case "$Path_target" in -*) Path_target="./$Path_target";; esac
 
     # --- Making the file --------------------------------------------
     case $optd in
@@ -247,12 +232,17 @@ for arg in "$@"; do
 
   # --- print error message when failed to make a file ---------------
   case "${optq}${n}" in
-    '0-1') echo "${0##*/}: failed on $Path_target" 1>&2; err=1; continue;;
-    '1-1')                                               err=1; continue;;
+    '0-1') printf '%s\n' "${0##*/}: failed on $Path_target" 1>&2
+           err=1
+           continue
+           ;;
+    '1-1') err=1
+           continue
+           ;;
   esac
 
   # --- print the path of the file -----------------------------------
-  echo "$Path_target"
+  printf '%s\n' "$Path_target"
 
   # --- remove the file if -u,--dry-run option is set ----------------
   case $optu in 1) rm -rf "$Path_target";; esac
diff --git a/sessionf b/sessionf
--- a/sessionf
+++ b/sessionf
@@ -39,7 +39,7 @@
 # * On "validate", "reuse" and "remove" subcommands, you can set the session
 #   file directory in the <id> argument instead of the "at" argument.
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/01/26
+# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/07
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -50,7 +50,7 @@
 # --- initalization --------------------------------------------------
 set -u
 PATH=/usr/bin:/bin
-Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d"; pwd)"
+Homedir=$(cd $(dirname "$0") && pwd)
 #
 if [ \( -f "${0%/*}/mkstemp" \) -a \( -x "${0%/*}/mkstemp" \) ]; then
   CMD_MKTEMP="${0%/*}/mkstemp"
@@ -61,7 +61,7 @@ fi
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} <subcommand> [argument] ...
-	Version : Fri Jun 27 07:07:46 JST 2014
+	Version : Sat Feb  7 01:46:59 JST 2015
 __USAGE
   exit 1
 }
@@ -73,29 +73,34 @@ dir=''
 idtmpl=''
 lifemin=''
 [ $# -ge 2 ] || print_usage_and_exit
-echo "_$1" | grep '^_[a-z]\{1,\}$' >/dev/null || print_usage_and_exit
+printf '%s\n' "$1" | grep -q '^[a-z]\{1,\}$' || print_usage_and_exit
 subcmd=$1
 shift
 if [ "$subcmd" != 'create' ]; then
   id=${1##*/}
-  echo "_$1" | grep '/' >/dev/null && dir=${1%/*} && [ -z "$dir" ] && dir='/'
+  printf '%s\n' "$1" | grep -q '/' && dir=${1%/*} && [ -z "$dir" ] && dir='/'
   shift
 fi
 for arg in "$@"; do
   case "$arg" in
     at=*)
       check=${arg#at=}
-      if echo "_$check" | grep '/' >/dev/null; then
+      if printf '%s\n' "$check" | grep -q '/'; then
         dir=${check%/*} && [ -z "$dir" ] && dir='/'
         idtmpl=${check##*/}
       else
         dir='.'
         idtmpl=$check
       fi
-      [ -d "$dir" ] || { echo "${0##*/}: directory not found"; exit 1; }
+      [ -d "$dir" ] || {
+        printf '%s\n' "${0##*/}: directory not found"
+        exit 1
+      }
       ;;
     lifemin=*)
-      echo "$arg" | grep '^lifemin=[0-9]\{1,\}$' >/dev/null || print_usage_and_exit
+      printf '%s\n' "$arg"                     |
+      grep '^lifemin=[0-9]\{1,\}$' >/dev/null ||
+      print_usage_and_exit
       lifemin=${arg#lifemin=}
       ;;
     *)
@@ -104,6 +109,7 @@ for arg in "$@"; do
   esac
 done
 [ -n "$dir" ] || print_usage_and_exit
+case "$dir" in -*) dir="./$dir";; esac
 
 # --- subcommand routines --------------------------------------------
 case $subcmd in
@@ -123,7 +129,7 @@ case $subcmd in
     find "$dir" -name "$id" -mmin +$lifemin | awk 'END{exit (NR>0) ? 1 : 0;}'
     [ $? -eq 0      ] || exit 2
     touch "$dir/$id"
-    echo "$dir/$id"
+    printf '%s\n' "$dir/$id"
     exit 0
     ;;
   avail)
@@ -133,7 +139,7 @@ case $subcmd in
     find "$dir" -name "$id" -mmin +$lifemin | awk 'END{exit (NR>0) ? 1 : 0;}'
     [ $? -eq 0      ] || exec $CMD_MKTEMP "$dir/$idtmpl"
     touch "$dir/$id"
-    echo "$dir/$id"
+    printf '%s\n' "$dir/$id"
     exit 0
     ;;
   renew)
@@ -147,7 +153,7 @@ case $subcmd in
     mv -f "$dir/$id" "$check"
     [ $? -eq 0      ] || exit 4
     touch "$check"
-    echo "$check"
+    printf '%s\n' "$check"
     exit 0
     ;;
   remove)
diff --git a/utf8wc b/utf8wc
--- a/utf8wc
+++ b/utf8wc
@@ -14,7 +14,7 @@
 #
 # Return : stdoutに半角換算文字数
 #
-# Written by Matsuura(richmikan@richlab.org) at 2013/11/02
+# Written by Matsuura(richmikan@richlab.org) at 2015/02/07
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -26,7 +26,7 @@
 print_usage_and_exit () {
   cat <<__USAGE 1>&2
 Usage   : ${0##*/} <file>
-Version : Sat Nov 2 13:52:50 JST 2013
+Version : Sat Feb  7 01:56:47 JST 2015
 __USAGE
   exit 1
 }
@@ -36,13 +36,14 @@ if [ \( -f "$1"      \) -o \
      \( -p "$1"      \) -o \
      \( "_$1" = '_-' \)    ]; then
   file="$1"
+  case "$file" in -) :;; -*) file="./$file";; esac
 elif [ $# -lt 1 ]; then
   file='-'
 else
   print_usage_and_exit
 fi
 if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the file" 1>&2
+  printf '%s\n' "${0##*/}: Cannot open the file" 1>&2
   exit 1
 fi
 
