added base64, and some improvements

diff --git a/gzpipe b/gzpipe
--- a/gzpipe
+++ b/gzpipe
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/sh -u
 
 ######################################################################
 #
@@ -47,7 +47,7 @@
 #   That means, you can join various filters to fd=2 (stderr). Although
 #   it is very tricky. ;-)
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/01/18
+# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/03
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -64,9 +64,27 @@ DEFAULT_TIMEOUT=600
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [-t timeout] <named_pipe_to_use> [output_file]
-	Version : Sun Jan 18 04:48:59 JST 2015
+	Version : Tue Feb  3 16:36:39 JST 2015
 __USAGE
   exit 1
+}
+
+# --- which command also works on Just a POSIX environment -----------
+which which >/dev/null 2>&1 || {
+  which () {
+    case "$1" in
+       /*) ls   "$1" 2>/dev/null; return $?;;
+      */*) ls "./$1" 2>/dev/null; return $?;;
+    esac
+    (
+      echo "$PATH" | tr ':' '\n' | while read dir; do
+        case "$dir" in '') break;; esac
+        ls "${dir%/}/$1" 2>/dev/null && exit 1 || continue
+      done
+      exit $((1-$?))
+    )
+    return $?
+  }
 }
 
 
@@ -91,6 +109,12 @@ done
 
 case $check in 'p')
 
+  # --- make sure that gzip command exists ---------------------------
+  which gzip >/dev/null 2>&1 || {
+    echo "${0##*/}: gzip command is not found" 1>&2
+    exit 1
+  }
+
   # --- exit trap (for parent) ---------------------------------------
   exit_trap() {
     trap EXIT HUP INT QUIT PIPE ALRM TERM
@@ -104,7 +128,7 @@ case $check in 'p')
   case "$1" in
     -t) shift
         case $# in                          0) print_usage_and_exit;; esac
-        printf '%s' "$1" | grep -q '[^0-9]' || print_usage_and_exit
+        printf '%s' "$1" | grep -q '[^0-9]' && print_usage_and_exit
         timeout=$1
         shift
         ;;
@@ -148,8 +172,8 @@ case $check in 'p')
   esac
 
   # --- make stderr silent -------------------------------------------
-  #exec 3>&2 2>/dev/null 1>&2 # fd3 is only available for debugging
-  exec 2>/dev/null 1>&2 3>&2
+  #exec 3>&2 2>/dev/null # fd3 is only available for debugging
+  exec 2>/dev/null 3>&2
 
   # --- prepare for locking ------------------------------------------
   sleep 100 & # This is to wait that the child process is ready
diff --git a/kata2hira b/kata2hira
--- a/kata2hira
+++ b/kata2hira
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/sh -u
 
 # base designed by Nobuaki Tounaka
 # written by 321516
@@ -12,7 +12,7 @@ print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [+<n>h] <f1> <f2> ... <file>
 	        : ${0##*/} -d <string>
-	Version : Fri Jun 27 01:42:19 JST 2014
+	Version : Sun Jan 18 23:10:21 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 __USAGE
   exit 1
@@ -31,11 +31,9 @@ opt_part=1
 hopt=0
 
 # parse the arguments
-if [ \( $# -eq 1 \) ]; then
-  case $1 in
-    -h|--help|--version) print_usage_and_exit;;
-  esac
-fi
+case "$#${1:-}" in
+  1-h|1--help|1--version) print_usage_and_exit;;
+esac
 i=0
 for arg in "$@"; do
   i=$((i+1))
@@ -46,16 +44,13 @@ for arg in "$@"; do
     continue
   elif [ \( $opt_part -ne 0 \) -a \( "_$arg" != "_${arg#+}" \) ]; then
     s=$(echo "_$arg" | sed 's/^_+\([0-9]*\)h$/\1/')
-    [ "_$s" != "_$arg" ] || print_usage_and_exit
-    [ -z "$s"          ] && { hopt=1; continue; }
+    case "$s" in "$arg") print_usage_and_exit;; esac
+    case "$s" in     '') hopt=1; continue    ;; esac
     hopt=$(expr $s + 0)
     continue
   fi
   opt_part=0
-  if [ \( $i -eq $# \) -a \( $directmode -ne 0 \) ]; then
-    directstr=$arg
-    break
-  fi
+  case "$i$directmode" in "${#}1") directstr=$arg; break;; esac
   # separate arg to arg1, arg2
   arg1=${arg%%/*}
   arg2=${arg##*/}
@@ -70,12 +65,10 @@ for arg in "$@"; do
   # check both
   j=0
   for s in $arg1 $arg2; do
-    if echo "_$s" | grep '^_[0-9]\{1,\}$' > /dev/null; then
+    if echo "_$s" | grep -q '^_[0-9]\{1,\}$'; then
       j=$((j+1))
-      if [ "$s" -eq 0 ]; then
-        all_fields=1
-      fi
-    elif echo "_$s" | grep -E '^_(NF|NF-[0-9]+)$' > /dev/null; then
+      case "$s" in 0) all_fields=1;; esac
+    elif echo "_$s" | grep -Eq '^_(NF|NF-[0-9]+)$'; then
       j=$((j+1))
     fi
   done
@@ -84,171 +77,169 @@ for arg in "$@"; do
     continue
   fi
   # perhaps, this argument is a filename
-  if [ $# -eq $i ]; then
-    file=$arg
-    continue
-  fi
+  case $# in $i) file=$arg; continue;; esac
   # otherwise, it is a invalid argument
   print_usage_and_exit
 done
 # (if you want to regard no fldnums as all, set all_fields=1 instead of exit)
-[ -n "$fldnums" ] || all_fields=1
-if [ $directmode -ne 0 ]; then
-  [ -n "$directstr" ] || print_usage_and_exit
-  file=''
-else
-  [ -n "$file" ] || file='-'
-  if [ \( "_$file" = '_-'               \) -o \
-       \( "_$file" = '_/dev/stdin'      \) -o \
-       \( "_$file" = '_/dev/fd/0'       \) -o \
-       \( "_$file" = '_/proc/self/fd/0' \)    ]
-  then
-    use_stdin=$((use_stdin+1))
-  fi
-  if [ \( ! -f "$file"     \) -a \
-       \( ! -c "$file"     \) -a \
-       \( ! -p "$file"     \) -a \
-       \( "_$file" != '_-' \)    ]
-  then
-    print_usage_and_exit
-  elif [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-    echo "${0##*/}: Cannot open the file" 1>&2
-    exit 1
-  fi
-fi
+case "$fldnums" in '') all_fields=1;; esac
+case $directmode in
+  0) case "$file" in '') file='-';; esac
+     if [ \( "_$file" = '_-'               \) -o \
+          \( "_$file" = '_/dev/stdin'      \) -o \
+          \( "_$file" = '_/dev/fd/0'       \) -o \
+          \( "_$file" = '_/proc/self/fd/0' \)    ]
+     then
+       use_stdin=$((use_stdin+1))
+     fi
+     if [ \( ! -f "$file"     \) -a \
+          \( ! -c "$file"     \) -a \
+          \( ! -p "$file"     \) -a \
+          \( "_$file" != '_-' \)    ]
+     then
+       print_usage_and_exit
+     elif [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
+       echo "${0##*/}: Cannot open the file" 1>&2
+       exit 1
+     fi
+     ;;
+  *) case "$directstr" in '') print_usage_and_exit;; esac
+     file=''
+     ;;
+esac
 
 # make the part of the awk code
-if [ $all_fields -eq 0 ]; then
-  awkc0=$(echo "$fldnums"                           |
-          sed 's/^0\{1,\}\([0-9]\)/\1/'             |
-          sed 's/\([^0-9]\)0\{1,\}\([0-9]\)/\1\2/g' |
-          tr ' ' '\n'                               |
-          awk                                       '
-            /^NF-[0-9]+\/NF-[0-9]+$/ {
-              nfofs1 = substr($0,4,index($0,"/")-4) + 0;
-              nfofs2 = substr($0,index($0,"/")+4) + 0;
-              if (nfofs1 > nfofs2) {
-                i = nfofs1;
-                nfofs1 = nfofs2;
-                nfofs2 = i;
-              }
-              for (i=nfofs1; i<=nfofs2; i++) {
-                print "0 NF-" i;
-              }
-            }
-            /^NF\/NF-[0-9]+$/ {
-              nfofs2 = substr($0,index($0,"/")+4);
-              print "0 NF";
-              for (i=1; i<=nfofs2; i++) {
-                print "0 NF-" i;
-              }
-            }
-            /^NF-[0-9]+\/NF$/ {
-              nfofs2 = substr($0,4,index($0,"/")-4) + 0;
-              print "0 NF";
-              for (i=1; i<=nfofs2; i++) {
-                print "0 NF-" i;
-              }
-            }
-            /^[0-9]+\/NF-[0-9]+$/ {
-              printf("0 %s NF-%s\n",
-                     substr($0,1,index($0,"/")-1),
-                     substr($0,index($0,"/")+4)   );
-            }
-            /^NF-[0-9]+\/[0-9]+$/ {
-              printf("0 %s NF-%s\n",
-                     substr($0,index($0,"/")+1),
-                     substr($0,4,index($0,"/")-4));
-            }
-            /^[0-9]+\/[0-9]+$/ {
-              pos = index($0, "/");
-              a = substr($0, 1, pos-1)+0;
-              b = substr($0, pos+1)+0;
-              if (a > b) {
-                swp = a;
-                a = b;
-                b = swp;
-              }
-              for (i=a; i<=b; i++) {
-                print 1, i;
-              }
-            }
-            /^[0-9]+\/NF$/ {
-              print 1, substr($0, 1, length($0)-3), "NF";
-            }
-            /^NF\/[0-9]+$/ {
-              print 1, substr($0, index($0,"/")+1), "NF";
-            }
-            /^[0-9]+$/ {
-              print 1, $0;
-            }
-            /^NF-[0-9]+$/ {
-              print 0, $0;
-            }
-            (($0 == "NF") || ($0 == "NF/NF")) {
-              print 0, "NF";
-            }
-          '                                         |
-          sort -k 1,1 -k 2n,2 -k 3n,3               |
-          uniq                                      |
-          sed -n '1,/1 [0-9]\{1,\} NF$/p'           |
-          awk                                       '
-            BEGIN {
-              f1_total  = 0;
-              f2_max    = 0;
-              f3_has_nf = 0;
-            }
-            {
-              f1_total += $1; 
-              if ($1 == 1) {
-                f2_max = ($2 > f2_max) ? $2 : f2_max;
-                f2_vals[$2] = 1;
-              }
-              f3_has_nf = ($3 == "NF") ? 1 : f3_has_nf;
-              cell[NR,1] = $2;
-              if (NF == 3) {
-                cell[NR,2] = $3;
-              }
-            }
-            END {
-              if ((f1_total == NR) && (f3_has_nf)) {
-                printf("split(\"\",mark);for(i=1;i<=NF;i++){mark[i]=1}");
-                for (i=1; i<f2_max; i++) {
-                  if (! (i in f2_vals)) {
-                    printf("delete mark[%d];", i);
-                  }
-                }
-              } else {
-                printf("split(\"\",mark);");
-                for (i=1; i<=NR; i++) {
-                  if (i SUBSEP 2 in cell) {
-                    printf("if(%s>%s){for(i=%s;i<=%s;i++){mark[i]=1}}else{for(i=%s;i<=%s;i++){mark[i]=1}}",
-                           cell[i,1],cell[i,2],
-                           cell[i,2],cell[i,1],
-                           cell[i,1],cell[i,2]);
-                  } else {
-                    if (match(cell[i,1],/^[0-9]+$/) || (cell[i,1] == "NF")) {
-                      printf("mark[%s]=1;",cell[i,1]);
-                    } else {
-                      printf("if(%s>0){mark[%s]=1}",cell[i,1],cell[i,1]);
-                    }
-                  }
-                }
-              }
-              printf("convert_marked_flds();print;");
-            }
-          '                                         )
-  echo "$awkc0" | grep 'NF' >/dev/null
-  if [ $? -ne 0 ]; then
-    awkc0b=${awkc0%convert_marked_flds*}
-    awkc0='convert_marked_flds();print;'
-  else
-    awkc0b=''
-  fi
-else
-  awkc0='print utf8kata2hira($0);'
-  awkc0b=''
-fi
+case $all_fields in
+  0) awkc0=$(echo "$fldnums"                           |
+             sed 's/^0\{1,\}\([0-9]\)/\1/'             |
+             sed 's/\([^0-9]\)0\{1,\}\([0-9]\)/\1\2/g' |
+             tr ' ' '\n'                               |
+             awk                                       '
+               /^NF-[0-9]+\/NF-[0-9]+$/ {
+                 nfofs1 = substr($0,4,index($0,"/")-4) + 0;
+                 nfofs2 = substr($0,index($0,"/")+4) + 0;
+                 if (nfofs1 > nfofs2) {
+                   i = nfofs1;
+                   nfofs1 = nfofs2;
+                   nfofs2 = i;
+                 }
+                 for (i=nfofs1; i<=nfofs2; i++) {
+                   print "0 NF-" i;
+                 }
+               }
+               /^NF\/NF-[0-9]+$/ {
+                 nfofs2 = substr($0,index($0,"/")+4);
+                 print "0 NF";
+                 for (i=1; i<=nfofs2; i++) {
+                   print "0 NF-" i;
+                 }
+               }
+               /^NF-[0-9]+\/NF$/ {
+                 nfofs2 = substr($0,4,index($0,"/")-4) + 0;
+                 print "0 NF";
+                 for (i=1; i<=nfofs2; i++) {
+                   print "0 NF-" i;
+                 }
+               }
+               /^[0-9]+\/NF-[0-9]+$/ {
+                 printf("0 %s NF-%s\n",
+                        substr($0,1,index($0,"/")-1),
+                        substr($0,index($0,"/")+4)   );
+               }
+               /^NF-[0-9]+\/[0-9]+$/ {
+                 printf("0 %s NF-%s\n",
+                        substr($0,index($0,"/")+1),
+                        substr($0,4,index($0,"/")-4));
+               }
+               /^[0-9]+\/[0-9]+$/ {
+                 pos = index($0, "/");
+                 a = substr($0, 1, pos-1)+0;
+                 b = substr($0, pos+1)+0;
+                 if (a > b) {
+                   swp = a;
+                   a = b;
+                   b = swp;
+                 }
+                 for (i=a; i<=b; i++) {
+                   print 1, i;
+                 }
+               }
+               /^[0-9]+\/NF$/ {
+                 print 1, substr($0, 1, length($0)-3), "NF";
+               }
+               /^NF\/[0-9]+$/ {
+                 print 1, substr($0, index($0,"/")+1), "NF";
+               }
+               /^[0-9]+$/ {
+                 print 1, $0;
+               }
+               /^NF-[0-9]+$/ {
+                 print 0, $0;
+               }
+               (($0 == "NF") || ($0 == "NF/NF")) {
+                 print 0, "NF";
+               }
+             '                                         |
+             sort -k 1,1 -k 2n,2 -k 3n,3               |
+             uniq                                      |
+             sed -n '1,/1 [0-9]\{1,\} NF$/p'           |
+             awk                                       '
+               BEGIN {
+                 f1_total  = 0;
+                 f2_max    = 0;
+                 f3_has_nf = 0;
+               }
+               {
+                 f1_total += $1; 
+                 if ($1 == 1) {
+                   f2_max = ($2 > f2_max) ? $2 : f2_max;
+                   f2_vals[$2] = 1;
+                 }
+                 f3_has_nf = ($3 == "NF") ? 1 : f3_has_nf;
+                 cell[NR,1] = $2;
+                 if (NF == 3) {
+                   cell[NR,2] = $3;
+                 }
+               }
+               END {
+                 if ((f1_total == NR) && (f3_has_nf)) {
+                   printf("split(\"\",mark);for(i=1;i<=NF;i++){mark[i]=1}");
+                   for (i=1; i<f2_max; i++) {
+                     if (! (i in f2_vals)) {
+                       printf("delete mark[%d];", i);
+                     }
+                   }
+                 } else {
+                   printf("split(\"\",mark);");
+                   for (i=1; i<=NR; i++) {
+                     if (i SUBSEP 2 in cell) {
+                       printf("if(%s>%s){for(i=%s;i<=%s;i++){mark[i]=1}}else{for(i=%s;i<=%s;i++){mark[i]=1}}",
+                              cell[i,1],cell[i,2],
+                              cell[i,2],cell[i,1],
+                              cell[i,1],cell[i,2]);
+                     } else {
+                       if (match(cell[i,1],/^[0-9]+$/) || (cell[i,1] == "NF")) {
+                         printf("mark[%s]=1;",cell[i,1]);
+                       } else {
+                         printf("if(%s>0){mark[%s]=1}",cell[i,1],cell[i,1]);
+                       }
+                     }
+                   }
+                 }
+                 printf("convert_marked_flds();print;");
+               }
+             '                                         )
+     if echo "$awkc0" | grep -q 'NF'; then
+       awkc0b=''
+     else
+       awkc0b=${awkc0%convert_marked_flds*}
+       awkc0='convert_marked_flds();print;'
+     fi
+     ;;
+  *) awkc0='print utf8kata2hira($0);'
+     awkc0b=''
+     ;;
+esac
 
 # make awk code
 awkcode='
@@ -351,9 +342,8 @@ function utf8kata2hira(s_in, i,s,s1,s2,utf8c,delta,s_out) {
 '
 
 # main
-if [ $directmode -ne 0 ]; then
-       printf '%s' "$directstr"               |
-       env - awk -v hdr_skip=$hopt "$awkcode"
-else
-  exec env - awk -v hdr_skip=$hopt "$awkcode" "$file"
-fi
+case $directmode in
+  0) exec env - awk -v hdr_skip=$hopt "$awkcode" "$file";;
+  *)      printf '%s' "$directstr"               |
+          env - awk -v hdr_skip=$hopt "$awkcode"        ;;
+esac
diff --git a/mkstemp b/mkstemp
--- a/mkstemp
+++ b/mkstemp
@@ -2,14 +2,13 @@
 
 ######################################################################
 #
-# MKSTEMP : A wrapper of mktemp(1) to behave as a equivalent of mkstemp(1)
+# MKSTEMP : A wrapper of mktemp(1) to behave as a equivalent of mkstemp(3)
 #
-# Usage  : mkstemp [mktemp(1)options] <template>
+# Usage  : mkstemp <mktemp(1)arguments>
 #
-# * <template> is necessary. And only 1.
 # * "mktemp(1) options" depend on mktemp(1) on the host
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) at 2013/11/09
+# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/01/26
 #
 # This is a public-domain software. It measns that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -22,75 +21,236 @@ print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [mktemp(1)options] <template>
 	          "mktemp(1) options" depend on mktemp(1) on the host.
-	Version : Sat Nov 09 23:23:10 JST 2013
+	Version : Mon Jan 26 15:22:35 JST 2015
 __USAGE
   exit 1
 }
 
-# --- definition: characters for substituting the "XXX..." string ----
+
+##### PREPARATION ####################################################
+
+# --- initialization -------------------------------------------------
+set -u
+PATH='/usr/bin:/bin'
+
+
+# --- use the built-in mktemp command if not need to do by myself ----
+which mktemp >/dev/null 2>&1
+case $? in
+  0) [ -f /etc/issue ] && grep -q '^CentOS.* 5\.[0-9]' /etc/issue
+     case $? in
+       0) do_by_myself=1;;
+       *) do_by_myself=0;;
+     esac                 ;;
+  *)      do_by_myself=1  ;;
+esac
+
+
+# --- call the bult-in mktemp if do_by_myself==0 ---------------------
+case $do_by_myself in
+  0) exec mktemp "$@";;
+esac
+
+
+
+##### DO MKTEMP BY MYSELF ############################################
+
+# ===== PREPARATION ==================================================
+
+# --- set the command path -------------------------------------------
+PATH='/usr/bin:/bin'
+
+# --- set the temporary directory ------------------------------------
+Dir_tmp=$(set | grep -q ^TMPDIR= | sed 's/^[^=]\{1,\}=//');
+case "$Dir_tmp" in
+  '') Dir_tmp='/tmp'      ;;
+  /)  Dir_tmp='/.'        ;;
+  *)  Dir_tmp=${Dir_tmp%/};;
+esac
+
+# --- misc -----------------------------------------------------------
 chrs='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_'
-xchrslen=$(echo "obase=16;${#chrs}" | bc)
+max_retry_when_failed=10
+LF=$(printf '\\\n_');LF=${LF%_}
 
-# --- parse the arguments --------------------------------------------
-[ $# -ge 1 ] || print_usage_and_exit
-i=1
-options=''
+
+# ===== OPTION PARSING ===============================================
+
+optd=0
+optu=0
+optq=0
+optt=0
+opts=''
+optmode=''
+while :; do
+  case "$optmode" in
+    '') case "$1" in
+          -[duqtp]*)   s=$(echo "_${1#-}"                                |
+                           awk '{d = "_"; u = "_"; q = "_";              #
+                                 t = "_"; p = "_"; err = 0;              #
+                                 for (i=2;i<=length($0);i++) {           #
+                                   s = substr($0,i,1);                   #
+                                   if      (s == "d") { d   = "d"; }     #
+                                   else if (s == "u") { u   = "u"; }     #
+                                   else if (s == "q") { q   = "q"; }     #
+                                   else if (s == "t") { t   = "t"; }     #
+                                   else if (s == "p") { p   =  p ; }     #
+                                   else               { err =  1 ; }     #
+                                 }                                       #
+                                 p = (substr($0,i-1)=="p") ? "p" : "_";  #
+                                 printf("%s%s%s%s%s%s",d,u,q,t,p,err); }')
+                       case "$s" in *1*) print_usage_and_exit;; esac
+                       case "$s" in *d*) optd=1              ;; esac
+                       case "$s" in *u*) optu=1              ;; esac
+                       case "$s" in *q*) optq=1              ;; esac
+                       case "$s" in *t*) optt=1              ;; esac
+                       case "$s" in *p*) optmode='p'         ;; esac
+                       shift; continue
+                       ;;
+          --directory) optd=1     ; shift; continue;;
+          --dry-run)   optu=1     ; shift; continue;;
+          --quiet)     optq=1     ; shift; continue;;
+          --tmpdir)                 shift; continue;;
+          --tmpdir=*)  optmode='p'
+                       s=${1#--tmpdir=}            ;;
+          --suffix=*)  optmode='s'
+                       s=${1#--suffix=}            ;;
+          -*)          print_usage_and_exit ;;
+        esac                                         ;;
+    *)  s=$1                                         ;;
+  esac
+  case "$optmode" in
+    p) [ -d "$s" ] || {
+         echo "${0##*/}: Invalid path by -p,--tmpdir option" 1>&2
+         exit 1
+       }
+       Dir_tmp=${s%/}; [ -n "$Dir_tmp" ] || Dir_tmp='/.'
+       optmode=''; shift; continue        ;;
+    s) { printf '%s' "$s" | grep -q '/'; } && {
+         echo "${0##*/}: Invalid suffix option" 1>&2
+         exit 1
+       }
+       opts=$s
+       optmode=''; shift; continue        ;;
+  esac
+  break
+done
+
+
+# ===== FUNC: random string generator ================================
+# arg   : $1=length
+# ret   : 0
+# stdout: generated random string
+random_string () {
+  # calculate the number of words which required
+  nw=$(echo "${1}*l(${#chrs})/11.09+1" | # 11.09=ln(65536)
+       bc -l                           |
+       sed 's/\..*$//'                 )
+
+  # make a random hexadecimal digit
+  if [ -c /dev/urandom ]; then
+    hstr=$(dd if=/dev/urandom bs=2 count=$nw 2>/dev/null |
+           od -A n -t x2 -v                              |
+           tr 'abcdef ' 'ABCDEF\n'                       |
+           tr -Cd 0123456789ABCDEF                       )
+  else
+    hstr=$( (ps -Ao pid,etime,pcpu,vsz; date)         |
+           od -t d4 -A n -v                           |
+           sed 's/[^0-9]\{1,\}/'"$LF"'/g'             |
+           grep '[0-9]'                               |
+           tail -n 42                                 |
+           sed 's/.*\(.\{8\}\)$/\1/g'                 |
+           awk 'BEGIN{a=-2147483648;}                 #
+                     {a+=$1;        }                 #
+                END  {                                #
+                  srand(a);                           #
+                  for(i=0;i<'$nw';i++){               #
+                    printf("%02X",int(rand()*65536)); #
+                  }                                   #
+                }'                                    )
+  fi
+
+  # make a random string from the hexadecimal digit
+  echo "obase=${#chrs};ibase=16;$hstr"         |
+  bc                                           |
+  tr -d '\\\n'                                 |
+  tr ' ' '\n'                                  |
+  awk 'BEGIN  {for(i=1;i<'$1';i++){print 0;}}  #
+       /[0-9]/{print;                       }' |
+  awk 'BEGIN  {ORS="";                         #
+               s="'"$chrs"'";                  #
+               for(i=0;i<length(s);i++){       #
+                 c[i]=substr(s,i+1,1);         #
+               }                        }      #
+       /[0-9]/{print c[$0*1];           }'     |
+  tail -c $1
+}
+
+
+# ===== MAKING LOOP ==================================================
+
+case $# in 0) optt=1; set -- 'tmp.XXXXXXXXXX';; esac
+
+err=0
 for arg in "$@"; do
-  if [ $i -lt $# ]; then
-    options="$options $arg"
-  else
-    template=$arg
-  fi
-  i=$((i+1))
-done
 
-# --- separate filepath ----------------------------------------------
-s=${template%/*}
-if [ "_$s" != "_$template" ]; then
-  path=$s
-else
-  path='.'
-fi
+  n=$max_retry_when_failed
+  while [ $n -ge 0 ]; do
 
-# --- count the number of the tail "X" characters --------------------
-template_without_x=$(echo "_$template" | sed '1s/^_//' | sed 's/X*$//')
-variable_len=$((${#template}-${#template_without_x}))
+    # --- Making the file path ---------------------------------------
+    #
+    # replace the end of "XXX..." string to a random one
+    Path_target=$arg
+    s=$(printf '%s' "$Path_target" | sed 's/X*$//')
+    i=$((${#Path_target}-${#s}))
+    case $i in
+      0) :                                    ;;
+      *) Path_target="${s}$(random_string $i)";;
+    esac
+    #
+    # add the suffix
+    Path_target="${Path_target}${opts}"
+    #
+    # add the prefix if the option -t is enabled
+    case $optt in 1) Path_target="${Dir_tmp}/${Path_target}";; esac
+    #
+    # normalize
+    Path_target=$(printf '%s' "$Path_target" |
+                  sed 's!//!/!g'             |
+                  sed 's!/./!/!g'            )
 
-# --- validate the path ----------------------------------------------
-[ -d "$path" ] || { echo "${0##*/}: No such directory" 1>&2; exit 1; }
+    # --- Making the file --------------------------------------------
+    case $optd in
+      0) (set -C; umask 177;   : > "$Path_target") 2>/dev/null || {
+           [ -f "$Path_target" ] && { n=$((n-1)); continue; }
+           n=-1; break;
+         }
+         ;;
+      1)          umask 077; mkdir "$Path_target"  2>/dev/null || {
+           [ -d "$Path_target" ] && { n=$((n-1)); continue; }
+           n=-1; break;
+         }
+         ;;
+    esac
 
-# --- make a temporary file (for non "X" terminated string) ----------
-if [ $variable_len -eq 0 ]; then
-  exec mktemp $options "$template_without_x"
-fi
-
-# --- make a temporary file (for "X" terminated string) --------------
-bytes=$(awk 'BEGIN{print int('$variable_len'*log('${#chrs}')/log(256))+1}')
-i=100  # <- time to retry
-while [ $i -gt 0 ]; do
-  i=$((i-1))
-  rndstr=$(cat /dev/urandom                                         |
-           head -c $bytes                                           |
-           od -v -An -tx1                                           |
-           tr -Cd '0-9a-fA-F'                                       |
-           tr 'a-f' 'A-F'                                           |
-           awk '{print "ibase=16; obase='$xchrslen'; " $1}'         |
-           bc                                                       |
-           tr -d '\\\n'                                             |
-           awk '{ORS="";                                            #
-                 split("'"$chrs"'",chrs,""); split($0,digits);      #
-                 for (pos in digits) {print chrs[digits[pos]+1];}}' |
-           head -c $variable_len                                    )
-  if [ $i -gt 0 ]; then
-    made_file=$(mktemp $options "$template_without_x$rndstr" 2>/dev/null)
-    [ $? -eq 0        ] || continue
-    [ -n "$made_file" ] || continue
     break
-  else
-    exec mktemp $options "$template_without_x$rndstr"
-  fi
-done
-echo "$made_file"
+  done
 
-# --- finish ---------------------------------------------------------
-exit 0
+  # --- print error message when failed to make a file ---------------
+  case "${optq}${n}" in
+    '0-1') echo "${0##*/}: failed on $Path_target" 1>&2; err=1; continue;;
+    '1-1')                                               err=1; continue;;
+  esac
+
+  # --- print the path of the file -----------------------------------
+  echo "$Path_target"
+
+  # --- remove the file if -u,--dry-run option is set ----------------
+  case $optu in 1) rm -rf "$Path_target";; esac
+
+done
+
+
+# ===== EXIT =========================================================
+
+exit $err
