mktemp,mkstemp: Integrated to mktemp and did a little refactoring

diff --git a/mkstemp b/mkstemp
--- a/mkstemp
+++ b/mkstemp
@@ -1,91 +1,94 @@
-#! /bin/sh
+#!/bin/sh
 
 ######################################################################
 #
-# MKSTEMP : A wrapper of mktemp(1) to behave as a equivalent of mkstemp(3)
+# MKTEMP - The "mktemp" Command Also Works On Just A POSIX Environment
 #
-# Usage  : mkstemp <mktemp(1)arguments>
+# USAGE: mktemp [--by-myself] [options] [template [...]]
 #
-# * "mktemp(1) options" depend on mktemp(1) on the host
+#        "--by-myself" ..... (write as the 1st argument when use)
+#                            Not use the "built-in" mktemp command
+#                            and always do mktemp by myself but it is
+#                            inferior to the built-in in performance
+#        "-d" .............. Make a directory instead of a file
+#        "-p [DIR]" ........ Define the temporary directory instead of
+#                            $TMPDIR
+#        "-q" .............. Quiet even if some error occurred
+#        "-u" .............. Make a file but remove it immediately
+#        "-t" .............. Add the temporary directory as a prefix
+#                            in front of the filepath
+#        "--suffix=<suff>" . Add the suffix behind the filename
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) at 2015/02/23
+# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-02-08
 #
-# This is a public-domain software. It measns that all of the people
-# can use this with no restrictions at all. By the way, I am fed up
-# the side effects which are broght about by the major licenses.
+# This is a public-domain software (CC0). It measns that all of the
+# people can use this for any purposes with no restrictions at all.
+# By the way, I am fed up the side effects which are broght about by
+# the major licenses.
 #
 ######################################################################
 
-# --- definition: print the usage and exit ---------------------------
-print_usage_and_exit () {
-  cat <<-__USAGE 1>&2
-	Usage   : ${0##*/} [mktemp(1)options] <template>
-	          "mktemp(1) options" depend on mktemp(1) on the host.
-	Version : Thu Jun 25 15:17:57 JST 2015
-__USAGE
-  exit 1
-}
 
+######################################################################
+# Initial Configuration
+######################################################################
 
-##### PREPARATION ####################################################
-
-# --- initialization -------------------------------------------------
+# === Initialize shell environment ===================================
 set -u
 umask 0022
-PATH='/usr/bin:/bin'
-IFS=$(printf ' \t\n_'); IFS=${IFS%_}
-export IFS LC_ALL=C LANG=C PATH
+export LC_ALL=C
+export PATH="$(command -p getconf PATH)${PATH:+:}${PATH:-}"
 
-# --- use the built-in mktemp command if not need to do by myself ----
-type mktemp >/dev/null 2>&1
-case $? in
-  0) [ -f /etc/issue ] && grep -q '^CentOS.* 5\.[0-9]' /etc/issue
-     case $? in
-       0) do_by_myself=1;;
-       *) do_by_myself=0;;
-     esac                 ;;
-  *)      do_by_myself=1  ;;
+# === Define the functions for printing usage and error message ======
+print_usage_and_exit () {
+  cat <<-USAGE 1>&2
+	Usage   : ${0##*/} [--by-myself] [options] [template [...]]
+	Version : 2017-02-08 22:13:53 JST
+	          (POSIX Bourne Shell/POSIX commands)
+	USAGE
+  exit 1
+}
+error_exit() {
+  [ -n "$2" ] && echo "${0##*/}: $2" 1>&2
+  exit $1
+}
+
+# === exec the mktemp command if exists ==============================
+case "${1:-}" in
+  --by-myself) shift                                                        ;;
+  *)           type mktemp >/dev/null 2>&1 && { exec mktemp "$@"; exit 1; } ;;
 esac
 
-
-# --- call the bult-in mktemp if do_by_myself==0 ---------------------
-case "$do_by_myself-$#" in
-  0-0) exec mktemp     ;;
-  0-*) exec mktemp "$@";;
-esac
-
-
-
-##### DO MKTEMP BY MYSELF ############################################
-
-# ===== PREPARATION ==================================================
-
-# --- set the command path -------------------------------------------
-PATH='/usr/bin:/bin'
-
-# --- set the temporary directory ------------------------------------
-Dir_tmp=$(set | grep -q ^TMPDIR= | sed 's/^[^=]\{1,\}=//');
+# === Investigate the temporary directory if set =====================
+Dir_tmp=$(set | grep ^TMPDIR= | sed 's/^[^=]\{1,\}=//');
 case "$Dir_tmp" in
   '') Dir_tmp='/tmp'      ;;
   /)  Dir_tmp='/.'        ;;
   *)  Dir_tmp=${Dir_tmp%/};;
 esac
 
-# --- misc -----------------------------------------------------------
+# === Misc definitions ===============================================
 chrs='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_'
 max_retry_when_failed=10
-LF=$(printf '\\\n_');LF=${LF%_}
+LFs=$(printf '\\\n_');LFs=${LFs%_}
 
 
-# ===== OPTION PARSING ===============================================
+######################################################################
+# Parse Arguments
+######################################################################
 
+# === Get the options and the filepath ===============================
+# --- initialize option parameters -----------------------------------
 optd=0
 optu=0
 optq=0
 optt=0
 opts=''
+#
+# --- get them -------------------------------------------------------
 optmode=''
 while [ $# -gt 0 ]; do
+  case $# in 0) break;; esac
   case "$optmode" in
     '') case "$1" in
           -[duqtp]*)   s=$(printf '%s\n' "${1#-}"                        |
@@ -123,15 +126,11 @@ while [ $# -gt 0 ]; do
     *)  s=$1                                         ;;
   esac
   case "$optmode" in
-    p) [ -d "$s" ] || {
-         printf '%s\n' "${0##*/}: Invalid path by -p,--tmpdir option" 1>&2
-         exit 1
-       }
+    p) [ -d "$s" ] || error_exit 1 'Invalid path by -p,--tmpdir option'
        Dir_tmp=${s%/}; [ -n "$Dir_tmp" ] || Dir_tmp='/.'
        optmode=''; shift; continue        ;;
     s) { printf '%s' "$s" | grep -q '/'; } && {
-         printf '%s\n' "${0##*/}: Invalid suffix option" 1>&2
-         exit 1
+         error_exit 1 'Invalid suffix option'
        }
        opts=$s
        optmode=''; shift; continue        ;;
@@ -139,6 +138,10 @@ while [ $# -gt 0 ]; do
   break
 done
 
+
+######################################################################
+# Prepare for the Main Routine
+######################################################################
 
 # ===== FUNC: random string generator ================================
 # arg   : $1=length
@@ -159,7 +162,7 @@ random_string () {
   else
     hstr=$( (ps -Ao pid,etime,pcpu,vsz; date)         |
            od -t d4 -A n -v                           |
-           sed 's/[^0-9]\{1,\}/'"$LF"'/g'             |
+           sed 's/[^0-9]\{1,\}/'"$LFs"'/g'            |
            grep '[0-9]'                               |
            tail -n 42                                 |
            sed 's/.*\(.\{8\}\)$/\1/g'                 |
@@ -190,12 +193,18 @@ random_string () {
 }
 
 
-# ===== MAKING LOOP ==================================================
+######################################################################
+# Main Routine
+######################################################################
 
 case $# in 0) optt=1; set -- 'tmp.XXXXXXXXXX';; esac
 
 err=0
 for arg in "$@"; do
+
+  # --- Make dir string for printing ---------------------------------
+  Dir_trg=${arg%/*}
+  case "$Dir_trg" in "$arg") Dir_trg='';; *) Dir_trg="$Dir_trg/";; esac
 
   n=$max_retry_when_failed
   while [ $n -ge 0 ]; do
@@ -204,7 +213,7 @@ for arg in "$@"; do
     #
     # replace the end of "XXX..." string to a random one
     Path_target=$arg
-    s=$(printf '%s' "$Path_target" | sed 's/X*$//')
+    s=$(printf '%s\n' "$Path_target" | sed 's/X*$//')
     i=$((${#Path_target}-${#s}))
     case $i in
       0) :                                    ;;
@@ -218,9 +227,9 @@ for arg in "$@"; do
     case $optt in 1) Path_target="${Dir_tmp}/${Path_target}";; esac
     #
     # normalize
-    Path_target=$(printf '%s' "$Path_target" |
-                  sed 's!//!/!g'             |
-                  sed 's!/./!/!g'            )
+    Path_target=$(printf '%s\n' "$Path_target" |
+                  sed 's!//!/!g'               |
+                  sed 's!/./!/!g'              )
     #
     # for security
     case "$Path_target" in
@@ -245,9 +254,9 @@ for arg in "$@"; do
     break
   done
 
-  # --- print error message when failed to make a file ---------------
+  # --- Print error message when failed to make a file ---------------
   case "${optq}${n}" in
-    '0-1') printf '%s\n' "${0##*/}: failed on $Path_target" 1>&2
+    '0-1') printf '%s\n' "${0##*/}: failed on $Dir_trg${Path_target##*/}" 1>&2
            err=1
            continue
            ;;
@@ -256,15 +265,17 @@ for arg in "$@"; do
            ;;
   esac
 
-  # --- print the path of the file -----------------------------------
-  printf '%s\n' "$Path_target"
+  # --- Print the path of the file -----------------------------------
+  printf '%s%s\n' "$Dir_trg" "${Path_target##*/}"
 
-  # --- remove the file if -u,--dry-run option is set ----------------
+  # --- Remove the file if -u,--dry-run option is set ----------------
   case $optu in 1) rm -rf "$Path_target";; esac
 
 done
 
 
-# ===== EXIT =========================================================
+######################################################################
+# Finish
+######################################################################
 
 exit $err
