*lock,*zpipe,greo,truncate: Refactoring, and Fixed a bug about error_exit calling

diff --git a/pexlock b/pexlock
--- a/pexlock
+++ b/pexlock
@@ -1,8 +1,8 @@
-#! /bin/sh
+#!/bin/sh
 
 ######################################################################
 #
-# PEXLOCK : A Exclusive Lock Command within POSIX
+# PEXLOCK - A Exclusive Lock Command within POSIX
 #
 # Usage   : pexlock [options] <lockname> [lockname ...]
 #           -d <lockdir> ...... the directory for lockfiles.
@@ -25,9 +25,9 @@
 #              :
 #           (do something requires exclusive lock)
 #              :
-#           touch -c "$lockid"    # extend lifetime if you want
-#              :                  # (but it needs to remain SUFFICIENT LIFETIME)
-#           punlock "$lockid"                               # release the lock
+#           touch -c "$lockid" # extend lifetime if you want
+#              :               # (but it needs to remain SUFFICIENT LIFETIME)
+#           punlock "$lockid"  # release the lock
 #
 # Notice  : The lockfile is written with rw-rw-rw for sharing.
 #           If you want not to share it with others,
@@ -42,45 +42,68 @@
 ######################################################################
 
 
-# ===== FUNCTIONS ====================================================
+######################################################################
+# Initial Configuration
+######################################################################
 
-# --- FUNC: print the usage and exit ---------------------------------
+# === Initialize shell environment ===================================
+set -u
+umask 0000 # <-- not 0022
+export LC_ALL=C
+export PATH="$(command -p getconf PATH)${PATH:+:}${PATH:-}"
+
+# === Define the functions for printing usage and error message ======
 print_usage_and_exit () {
-  cat <<-__USAGE 1>&2
+  cat <<-USAGE 1>&2
 	Usage   : ${0##*/} [options] <lockname> [lockname ...]
-	          -d <lockdir> ...... the directory for lockfiles.
+	Options : -d <lockdir> ...... the directory for lockfiles.
 	                              The lockfile directory will be decided
 	                              as the following rule.
 	                              1) this option "-d" if specified
 	                              2) the environment varriable "PLOCKDIR"
 	                                 if specified
 	                              3) if the environment varriable "TMPDIR"
-	                                 specified, "\$TMPDIR/plock.<username>"
+	                                 specified, "$TMPDIR/plock.<username>"
 	                              4) "/tmp/plock.<username>" (default)
 	          -w <maxwaiting> ... maximum waiting seconds to succeed locking
 	                              (-1 means waiting infinitely)
 	                              The default value is 10.
+	Return  : $?     ==0 ... one or more locking were success
+	                 !=0 ... all failure
+	          stdout ....... generated path of the lockfile
+	Example : lockid=$(pexlock -d /tmp/plock -w 10 foo) || exit 1 # do ex-lock
+	             :
+	          (do something requires exclusive lock)
+	             :
+	          touch -c "$lockid" # extend lifetime if you want
+	             :               # (but it needs to remain SUFFICIENT LIFETIME)
+	          punlock "$lockid"  # release the lock
+	Notice  : The lockfile is written with rw-rw-rw for sharing.
+	          If you want not to share it with others,
+	          you have to give the lockdir rwxrwx--- or rwx------ permisson.
 	Version : 2017-02-24 00:38:02 JST
-__USAGE
+	USAGE
   exit 1
+}
+warning() {
+  ${1+:} false && echo "${0##*/}: $1" 1>&2
+}
+error_exit() {
+  ${2+:} false && echo "${0##*/}: $2" 1>&2
+  exit $1
 }
 
 
+######################################################################
+# Argument Parsing
+######################################################################
 
-# ===== PREPARATION ==================================================
-
-# --- initialize -----------------------------------------------------
-set -u
-PATH='/usr/bin:/bin'
-IFS=$(printf ' \t\n_'); IFS=${IFS%_}
-export IFS LC_ALL=C LANG=C PATH
-umask 0000
-
-# --- parse the arguments --------------------------------------------
-dopt=''
+# === Set default values =============================================
+optd=''
 max_waiting_secs=10
 max_lifetime_secs=''
-ppid=$(ps -Ao pid,ppid | awk '$1=='"$$"'{print $2;exit}')
+
+# === Parse arguments ================================================
 optmode=''
 while [ $# -gt 0 ]; do
   case "$optmode" in
@@ -99,7 +122,7 @@ while [ $# -gt 0 ]; do
                    ret2=${ret#* }
                    case "$ret1$ret2" in
                      d)  optmode='d'             ;;
-                     d*) dopt=$ret2              ;;
+                     d*) optd=$ret2              ;;
                      w)  optmode='w'             ;;
                      w*) max_waiting_secs=$ret2  ;;
                      l)  optmode='l'             ;;
@@ -112,7 +135,7 @@ while [ $# -gt 0 ]; do
                    ;;
         esac
         ;;
-    d)  dopt=$1
+    d)  optd=$1
         optmode=''
         ;;
     w)  max_waiting_secs=$1
@@ -124,18 +147,19 @@ while [ $# -gt 0 ]; do
   esac
   shift
 done
+
+# === Validate arguments =============================================
 case $# in 0) print_usage_and_exit;; esac
 echo "_$max_waiting_secs"   | grep -Eq '^_-?[0-9]+$' || {
-  printf '%s: Maximum waiting seconds parameter is invalid\n' "${0##*/}" 1>&2
-  exit 1
+  error_exit 1 'Maximum waiting seconds parameter is invalid'
 }
 case "$max_lifetime_secs" in
-  '') :                                                                       ;;
-   *) printf '%s: option "-l" could not use in this command\n' "${0##*/}" 1>&2;;
+  '') :                                                  ;;
+   *) warning 'option "-l" could not use in this command';;
 esac
 Dir_lock=''
 while :; do
-  case "$dopt"         in '') :;; *) Dir_lock="${dopt%/}/"
+  case "$optd"         in '') :;; *) Dir_lock="${optd%/}/"
                                      break                             ;; esac
   case "${PLOCKDIR:-}" in '') :;; *) Dir_lock="${PLOCKDIR%/}/"
                                      break                             ;; esac
@@ -147,18 +171,19 @@ while :; do
                                      break                             ;; esac
 done
 case $? in
-  [!0]*) echo "${0##*/}: Failed to make the lockfile directory" 1>&2;exit 1;;
+  [!0]*) error_exit 1 'Failed to make the lockfile directory';;
 esac
-[ \( -z "$dopt" \) -o \( -d "$dopt" \) ] || {
-  echo "${0##*/}: \"$Dir_lock\": No such directory or permission denied" 1>&2
-  exit 1
+[ -z "$optd" ] || [ -d "$optd" ] || {
+  error_exit 1 'No such directory or permission denied: '"$Dir_lock"
 }
 case "$Dir_lock" in [!/]*) s=$(pwd);Dir_lock="${s%/}/$Dir_lock";; esac
 
 
+######################################################################
+# Main Routine
+######################################################################
 
-# ===== MAIN =========================================================
-
+ppid=$(ps -Ao pid,ppid | awk '$1=='"$$"'{print $2;exit}')
 count_all=0
 count_success=0
 for lockname in "$@"; do
@@ -166,14 +191,12 @@ for lockname in "$@"; do
 
   # --- Validate the lockname  ---------------------------------------
   case "$lockname" in '.border_date_and_time.tmp')
-    printf '%s: ".border_date_and_time.tmp" is reserved, skipped\n' \
-           "${0##*/}" 1>&2
+    warning '".border_date_and_time.tmp" is reserved, skipped'
     continue
     ;;
   esac
   echo "_$lockname" | grep -q '[/:]' && {
-    printf '%s: "%s": Neither "/" nor ":" can be used in lockname, skipped\n' \
-           "${0##*/}" "$lockname" 1>&2
+    warning "$lockname"': Neither "/" nor ":" can be used in lockname, skipped'
     continue
   }
 
@@ -201,11 +224,10 @@ for lockname in "$@"; do
   case $try in
     [1-9]*) printf '%s%s\n' "$Dir_lock" "${lockname}"
             ;;
-         0) printf '%s: "%s": timeout, try again later\n' \
-                   "${0##*/}" "$lockname" 1>&2
+         0) warning "$lockname"': timeout, try again later'
             continue
             ;;
-        -*) printf '%s: "%s": unexpedter error!\n' "${0##*/}" "$lockname" 1>&2
+        -*) warning "$lockname"': unexpedter error!'
             continue
             ;;
   esac
@@ -214,10 +236,11 @@ for lockname in "$@"; do
 done
 
 
+######################################################################
+# Finish
+######################################################################
 
-# ===== FINISH =======================================================
-
-# --- Return 1 if all locking failed ---------------------------------
+# === Return 1 if all locking failed =================================
 case "$count_success:$count_all" in
   0:[!0]*) exit 1;;
         *) exit 0;;
diff --git a/pshlock b/pshlock
--- a/pshlock
+++ b/pshlock
@@ -1,8 +1,8 @@
-#! /bin/sh
+#!/bin/sh
 
 ######################################################################
 #
-# PSHLOCK : A Shared Lock (and Semaphore) Command within POSIX
+# PSHLOCK - A Shared Lock (and Semaphore) Command within POSIX
 #
 # Usage   : pshlock [options] <lockname> [lockname ...]
 #           -n <maxsharing> ... the maximum number of sharing lock
@@ -25,19 +25,19 @@
 #                  !=0 ... all failure
 #           stdout ....... enerated path of the lockfile (just lock-id)
 #
-# Example : lockid=$(pshlock -n 5 -d /tmp/plock -w 10 foo) || exit 1 #do sh-lock
-#              :
+# Example : lockid=$(pshlock -n 5 -d /tmp/plock -w 10 foo) || exit 1 #do
+#              :                                                     #sh-lock
 #           (do something requires shared lock among up to 5 processes)
 #              :
-#           touch -c "$lockid"    # extend lifetime if you want
-#              :                  # (but it needs to remain SUFFICIENT LIFETIME)
-#           punlock "$lockid"                               # release the lock
+#           touch -c "$lockid" # extend lifetime if you want
+#              :               # (but it needs to remain SUFFICIENT LIFETIME)
+#           punlock "$lockid"  # release the lock
 #
 # Notice  : The lockfile is written with rw-rw-rw for sharing.
 #           If you want not to share it with others,
 #           you have to give the lockdir rwxrwx--- or rwx------ permisson.
 #
-# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-02-24
+# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-02-26
 #
 # This is a public-domain software. It means that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -46,13 +46,21 @@
 ######################################################################
 
 
-# ===== FUNCTIONS ====================================================
+######################################################################
+# Initial Configuration
+######################################################################
 
-# --- FUNC: print the usage and exit ---------------------------------
+# === Initialize shell environment ===================================
+set -u
+umask 0000 # <-- not 0022
+export LC_ALL=C
+export PATH="$(command -p getconf PATH)${PATH:+:}${PATH:-}"
+
+# === Define the functions for printing usage and error message ======
 print_usage_and_exit () {
-  cat <<-__USAGE 1>&2
+  cat <<-USAGE 1>&2
 	Usage   : ${0##*/} [options] <lockname> [lockname ...]
-	          -n <maxsharing> ... the maximum number of sharing lock
+	Options :  -n <maxsharing> ... the maximum number of sharing lock
 	                              This option is for using as a semaphore.
 	                              The default value is -1.
 	                              (-1 means infinity that is sharing lock)
@@ -63,7 +71,7 @@ print_usage_and_exit () {
 	                              2) the environment varriable "PLOCKDIR"
 	                                 if specified
 	                              3) if the environment varriable "TMPDIR"
-	                                 specified, "\$TMPDIR/plock.<username>"
+	                                 specified, "$TMPDIR/plock.<username>"
 	                              4) "/tmp/plock.<username>" (default)
 	          -w <maxwaiting> ... maximum waiting seconds to succeed locking
 	                              (-1 means waiting infinitely)
@@ -71,14 +79,27 @@ print_usage_and_exit () {
 	Return  : $?     ==0 ... one or more locking were success
 	                 !=0 ... all failure
 	          stdout ....... enerated path of the lockfile (just lock-id)
-	Version : 2017-02-24 00:38:02 JST
-__USAGE
+	Example : lockid=$(pshlock -n 5 -d /tmp/plock -w 10 foo) || exit 1 #<do
+	             :                                                     # sh-lock
+	          (do something requires shared lock among up to 5 processes)
+	             :
+	          touch -c "$lockid" # extend lifetime if you want
+	             :               # (but it needs to remain SUFFICIENT LIFETIME)
+	          punlock "$lockid"  # release the lock
+	Notice  : The lockfile is written with rw-rw-rw for sharing.
+	          If you want not to share it with others,
+	          you have to give the lockdir rwxrwx--- or rwx------ permisson.
+	Version : 2017-02-26 11:51:40 JST
+	USAGE
   exit 1
 }
-
-# --- FUNC: exit-trap ------------------------------------------------
-# arg   : [return code]
-# ret   : (not return)
+warning() {
+  ${1+:} false && echo "${0##*/}: $1" 1>&2
+}
+error_exit() {
+  ${2+:} false && echo "${0##*/}: $2" 1>&2
+  exit $1
+}
 exit_trap () {
   trap - EXIT HUP INT QUIT PIPE ALRM TERM
   rm -rf "${Dir_prelk:-}" "${File_modlk:-}" >/dev/null 2>&1
@@ -87,22 +108,17 @@ exit_trap () {
 }
 
 
+######################################################################
+# Argument Parsing
+######################################################################
 
-# ===== PREPARATION ==================================================
-
-# --- initialize -----------------------------------------------------
-set -u
-PATH='/usr/bin:/bin'
-IFS=$(printf ' \t\n_'); IFS=${IFS%_}
-export IFS LC_ALL=C LANG=C PATH
-umask 0000
-
-# --- parse the arguments --------------------------------------------
+# === Set default values =============================================
 max_num_of_sharing=-1
-dopt=''
+optd=''
 max_waiting_secs=10
 max_lifetime_secs=''
-ppid=$(ps -Ao pid,ppid | awk '$1=='"$$"'{print $2;exit}')
+
+# === Parse arguments ================================================
 optmode=''
 while [ $# -gt 0 ]; do
   case "$optmode" in
@@ -123,7 +139,7 @@ while [ $# -gt 0 ]; do
                       n)  optmode='n'             ;;
                       n*) max_num_of_sharing=$ret2;;
                       d)  optmode='d'             ;;
-                      d*) dopt=$ret2              ;;
+                      d*) optd=$ret2              ;;
                       w)  optmode='w'             ;;
                       w*) max_waiting_secs=$ret2  ;;
                       l)  optmode='l'             ;;
@@ -139,7 +155,7 @@ while [ $# -gt 0 ]; do
     n)  max_num_of_sharing=$1
         optmode=''
         ;;
-    d)  dopt=$1
+    d)  optd=$1
         optmode=''
         ;;
     w)  max_waiting_secs=$1
@@ -151,22 +167,22 @@ while [ $# -gt 0 ]; do
   esac
   shift
 done
+
+# === Validate arguments =============================================
 case $# in 0) print_usage_and_exit;; esac
 echo "_$max_num_of_sharing" | grep -Eq '^_-?[0-9]+$' || {
-  printf '%s: Maximum number of sharing parameter is invalid\n' "${0##*/}" 1>&2
-  exit 1
+  error_exit 1 'Maximum number of sharing parameter is invalid'
 }
 echo "_$max_waiting_secs"   | grep -Eq '^_-?[0-9]+$' || {
-  printf '%s: Maximum waiting seconds parameter is invalid\n' "${0##*/}" 1>&2
-  exit 1
+  error_exit 1 'Maximum waiting seconds parameter is invalid'
 }
 case "$max_lifetime_secs" in
-  '') :                                                                       ;;
-   *) printf '%s: option "-l" could not use in this command\n' "${0##*/}" 1>&2;;
+  '') :                                                  ;;
+   *) warning 'option "-l" could not use in this command';;
 esac
 Dir_lock=''
 while :; do
-  case "$dopt"         in '') :;; *) Dir_lock="${dopt%/}/"
+  case "$optd"         in '') :;; *) Dir_lock="${optd%/}/"
                                      break                             ;; esac
   case "${PLOCKDIR:-}" in '') :;; *) Dir_lock="${PLOCKDIR%/}/"
                                      break                             ;; esac
@@ -178,19 +194,20 @@ while :; do
                                      break                             ;; esac
 done
 case $? in
-  [!0]*) echo "${0##*/}: Failed to make the lockfile directory" 1>&2;exit 1;;
+  [!0]*) error_exit 1 'Failed to make the lockfile directory';;
 esac
-[ \( -z "$dopt" \) -o \( -d "$dopt" \) ] || {
-  echo "${0##*/}: \"$Dir_lock\": No such directory or permission denied" 1>&2
-  exit 1
+[ -z "$optd" ] || [ -d "$optd" ] || {
+  error_exit 1 'No such directory or permission denied: '"$Dir_lock"
 }
 case "$Dir_lock" in [!/]*) s=$(pwd);Dir_lock="${s%/}/$Dir_lock";; esac
 
 
-
-# ===== MAIN =========================================================
+######################################################################
+# Main Routine
+######################################################################
 
 trap 'exit_trap' EXIT HUP INT QUIT PIPE ALRM TERM
+ppid=$(ps -Ao pid,ppid | awk '$1=='"$$"'{print $2;exit}')
 count_all=0
 count_success=0
 for lockname in "$@"; do
@@ -198,18 +215,16 @@ for lockname in "$@"; do
 
   # --- Validate the lockname  ---------------------------------------
   case "$lockname" in '.border_date_and_time.tmp')
-    printf '%s: ".border_date_and_time.tmp" is reserved, skipped\n' \
-           "${0##*/}" 1>&2
+    warning '".border_date_and_time.tmp" is reserved, skipped'
     continue
     ;;
   esac
   echo "_$lockname" | grep -q '[/:]' && {
-    printf '%s: "%s": Neither "/" nor ":" can be used in lockname, skipped\n' \
-           "${0##*/}" "$lockname" 1>&2
+    warning "$lockname"': Neither "/" nor ":" can be used in lockname, skipped'
     continue
   }
   echo "_$lockname" | grep -Eq '^_\.preshlock\.[0-9]{14}\.[0-9]+\.[0-9]+$' && {
-    echo "${0##*/}: \"$lockname\": '/' is reserved, skip" 1>&2
+    warning "$lockname: '/' is reserved, skip"
     continue
   }
 
@@ -221,7 +236,7 @@ for lockname in "$@"; do
   Dir_prelk="${Dir_lock}.preshlock.$sublockname"
   mkdir "$Dir_prelk"
   case $? in [!0]*)
-    echo "${0##*/}: \"$lockname\": Failed to make a pre-lock dir #1" 1>&2
+    warning "$lockname"': Failed to make a pre-lock dir #1'
     continue
     ;;
   esac
@@ -230,7 +245,7 @@ for lockname in "$@"; do
   #     when the samenamed lock directory already exists.)
   mkdir -p "$Dir_prelk/$lockname/$lockname/$sublockname"
   case $? in [!0]*)
-    echo "${0##*/}: \"$lockname\": Failed to make a pre-lock dir #2" 1>&2
+    warning "$lockname"': Failed to make a pre-lock dir #2'
     continue
     ;;
   esac
@@ -263,7 +278,7 @@ for lockname in "$@"; do
     }
     # 1-3) check the current number of the locking processes
     n=$(ls -ld . 2>/dev/null | awk '{print $2-2;}')
-    [ \( $max_num_of_sharing -lt 0 \) -o \( $n -lt $max_num_of_sharing \) ] || {
+    [ $max_num_of_sharing -lt 0 ] || [ $n -lt $max_num_of_sharing ] || {
       rm -f 'modifying' 2>/dev/null                   # retry  if reached limit
       File_modlk=''
       [ $max_waiting_secs -ge 0 ] && try=$((try-1))
@@ -293,15 +308,13 @@ for lockname in "$@"; do
     [1-9]*) printf '%s%s/%s/%s\n'                                           \
                    "$Dir_lock" "${lockname}" "${lockname}" "$sublockname"
             ;;
-         0) printf '%s: "%s": timeout, try again later\n' \
-                   "${0##*/}" "$lockname" 1>&2
+         0) warning "$lockname"': timeout, try again later'
             err=1
             ;;
-        -1) printf '%s: "%s": timeout, the lock-dir is broken!\n' \
-                   "${0##*/}" "$lockname" 1>&2
+        -1) warning "$lockname"': timeout, the lock-dir is broken!'
             err=1
             ;;
-        -*) printf '%s: "%s": unexpedter error!\n' "${0##*/}" "$lockname" 1>&2
+        -*) warning "$lockname"': unexpedter error!'
             err=1
             ;;
   esac
@@ -314,10 +327,11 @@ for lockname in "$@"; do
 done
 
 
+######################################################################
+# Finish
+######################################################################
 
-# ===== FINISH =======================================================
-
-# --- Return 1 if all locking failed ---------------------------------
+# === Return 1 if all locking failed =================================
 case "$count_success:$count_all" in
   0:[!0]*) exit_trap 1;;
         *) exit_trap 0;;
diff --git a/punlock b/punlock
--- a/punlock
+++ b/punlock
@@ -1,8 +1,8 @@
-#! /bin/sh
+#!/bin/sh
 
 ######################################################################
 #
-# PUNLOCK : A Unlock Command for "pexlock" and "pshlock"
+# PUNLOCK - A Unlock Command for "pexlock" and "pshlock"
 #
 # Usage   : punlock [options] <lockname> [lockname ...]
 #           -d <lockdir> ...... the directory for lockfiles.
@@ -25,7 +25,7 @@
 #           If you want not to share it with others,
 #           you have to give the lockdir rwxrwx--- or rwx------ permisson.
 #
-# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-02-24
+# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-02-26
 #
 # This is a public-domain software. It means that all of the people
 # can use this with no restrictions at all. By the way, I am fed up
@@ -34,13 +34,21 @@
 ######################################################################
 
 
-# ===== FUNCTIONS ====================================================
+######################################################################
+# Initial Configuration
+######################################################################
 
-# --- FUNC: print the usage and exit ---------------------------------
+# === Initialize shell environment ===================================
+set -u
+umask 0000 # <-- not 0022
+export LC_ALL=C
+export PATH="$(command -p getconf PATH)${PATH:+:}${PATH:-}"
+
+# === Define the functions for printing usage and error message ======
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [options] <lockname> [lockname ...]
-	          -d <lockdir> ...... the directory for lockfiles.
+	Options : -d <lockdir> ...... the directory for lockfiles.
 	                              The lockfile directory will be decided
 	                              as the following rule.
 	                              1) this option "-d" if specified
@@ -51,14 +59,23 @@ print_usage_and_exit () {
 	                              maximum waiting seconds to succeed locking
 	                              (-1 means waiting infinitely)
 	                              The default value is 10.
-	Version : 2017-02-24 00:38:02 JST
+	Return  : ==0 ... one or more unlocking were success
+	          !=0 ... all failure
+	Example : See the header comments of "pexlock" and "pshlock"
+	Notice  : The lockfile is written with rw-rw-rw for sharing.
+	          If you want not to share it with others,
+	          you have to give the lockdir rwxrwx--- or rwx------ permisson.
+	Version : 2017-02-26 11:53:37 JST
 __USAGE
   exit 1
 }
-
-# --- FUNC: exit-trap ------------------------------------------------
-# arg   : [return code]
-# ret   : (not return)
+warning() {
+  ${1+:} false && echo "${0##*/}: $1" 1>&2
+}
+error_exit() {
+  ${2+:} false && echo "${0##*/}: $2" 1>&2
+  exit $1
+}
 exit_trap () {
   trap - EXIT HUP INT QUIT PIPE ALRM TERM
   rm -rf "${File_modlk:-}" >/dev/null 2>&1
@@ -66,21 +83,16 @@ exit_trap () {
 }
 
 
+######################################################################
+# Argument Parsing
+######################################################################
 
-# ===== PREPARATION ==================================================
-
-# --- initialize -----------------------------------------------------
-set -u
-PATH='/usr/bin:/bin'
-IFS=$(printf ' \t\n_'); IFS=${IFS%_}
-export IFS LC_ALL=C LANG=C PATH
-umask 0000
-
-# --- parse the arguments --------------------------------------------
-dopt=''
+# === Set default values =============================================
+optd=''
 max_waiting_secs=10
 max_lifetime_secs=''
-ppid=$(ps -Ao pid,ppid | awk '$1=='"$$"'{print $2;exit}')
+
+# === Parse arguments ================================================
 optmode=''
 while [ $# -gt 0 ]; do
   case "$optmode" in
@@ -99,7 +111,7 @@ while [ $# -gt 0 ]; do
                    ret2=${ret#* }
                    case "$ret1$ret2" in
                      d)  optmode='d'             ;;
-                     d*) dopt=$ret2              ;;
+                     d*) optd=$ret2              ;;
                      w)  optmode='w'             ;;
                      w*) max_waiting_secs=$ret2  ;;
                      l)  optmode='l'             ;;
@@ -112,7 +124,7 @@ while [ $# -gt 0 ]; do
                    ;;
         esac
         ;;
-    d)  dopt=$1
+    d)  optd=$1
         optmode=''
         ;;
     w)  max_waiting_secs=$1
@@ -124,18 +136,19 @@ while [ $# -gt 0 ]; do
   esac
   shift
 done
+
+# === Validate arguments =============================================
 case $# in 0) print_usage_and_exit;; esac
 echo "_$max_waiting_secs"   | grep -Eq '^_-?[0-9]+$' || {
-  printf '%s: Maximum waiting seconds parameter is invalid\n' "${0##*/}" 1>&2
-  exit 1
+  error_exit 1 'Maximum waiting seconds parameter is invalid'
 }
 case "$max_lifetime_secs" in
-  '') :                                                                       ;;
-   *) printf '%s: option "-l" could not use in this command\n' "${0##*/}" 1>&2;;
+  '') :                                                  ;;
+   *) warning 'option "-l" could not use in this command';;
 esac
 Dir_lock=''
 while :; do
-  case "$dopt"         in '') :;; *) Dir_lock="${dopt%/}/"
+  case "$optd"         in '') :;; *) Dir_lock="${optd%/}/"
                                      break                             ;; esac
   case "${PLOCKDIR:-}" in '') :;; *) Dir_lock="${PLOCKDIR%/}/"
                                      break                             ;; esac
@@ -144,20 +157,21 @@ while :; do
                                      break                             ;; esac
 done
 case $? in
-  [!0]*) echo "${0##*/}: Failed to make the lockfile directory" 1>&2;exit 1;;
+  [!0]*) error_exit 1 'Failed to make the lockfile directory';;
 esac
-[ \( -z "$dopt" \) -o \( -d "$dopt" \) ] || {
-  echo "${0##*/}: \"$Dir_lock\": No such directory or permission denied" 1>&2
-  exit 1
+[ -z "$optd" ] || [ -d "$optd" ] || {
+  error_exit 1 'No such directory or permission denied: '"$Dir_lock"
 }
 case "$Dir_lock" in [!/]*) s=$(pwd);Dir_lock="${s%/}/$Dir_lock";; esac
 
 
+######################################################################
+# Main Routine
+######################################################################
 
-# ===== MAIN =========================================================
-
-Dir_home=$(pwd);Dir_home=${Dir_home%/}
 trap 'exit_trap' EXIT HUP INT QUIT PIPE ALRM TERM
+ppid=$(ps -Ao pid,ppid | awk '$1=='"$$"'{print $2;exit}')
+Dir_home=$(pwd);Dir_home=${Dir_home%/}
 count_all=0
 count_success=0
 for lockname in "$@"; do
@@ -188,22 +202,20 @@ for lockname in "$@"; do
   Dir_path="${lockname%/*}/"
   lockname="${lockname##*/}"
   # 3) skip if the argument is a sh-lock without sublock-id
-  [ \( -d "$Dir_path$lockname" \) -a \( -z "$sublockname" \) ] && {
-    printf '%s: "%s": It is a sh-lockfile, but without sublock-id\n' \
-           "${0##*/}" "$lockname" 1>&2
+  [ -d "$Dir_path$lockname" ] && [ -z "$sublockname" ] && {
+    warning "$lockname"': It is a sh-lockfile, but without sublock-id'
     continue
   }
   # 4) skip if the argument is one of some reserve names
   case "$lockname" in
     '.border_date_and_time.tmp')
-      printf '%s: ".border_date_and_time.tmp" is reserved, skip\n' "${0##*/}" \
-             1>&2
+      warning '".border_date_and_time.tmp" is reserved, skipped'
       continue
       ;;
   esac
   printf '%s\n' "$lockname"                              |
   grep -Eq '^\.preshlock\.[0-9]{14}\.[0-9]+\.[0-9]+$' && {
-    echo "${0##*/}: \"$lockname\": '/' is reserved, skip" 1>&2
+    warning "$lockname: '/' is reserved, skipped"
     continue
   }
 
@@ -265,13 +277,11 @@ for lockname in "$@"; do
   case $try in
     [1-9]*) :
             ;;
-         0) printf '%s: "%s": timeout, try again later\n' \
-                   "${0##*/}" "$lockname" 1>&2
+         0) warning "$lockname"': timeout, try again later'
             ;;
-        -1) printf '%s: "%s": timeout, the lock-dir is broken!\n' \
-                   "${0##*/}" "$lockname" 1>&2
+        -1) warning "$lockname"': timeout, the lock-dir is broken!'
             ;;
-        -*) printf '%s: "%s": unexpedter error!\n' "${0##*/}" "$lockname" 1>&2
+        -*) warning "$lockname"': unexpedter error!'
             ;;
   esac
 
@@ -279,11 +289,12 @@ for lockname in "$@"; do
 done
 
 
+######################################################################
+# Finish
+######################################################################
 
-# ===== FINISH =======================================================
-
-# --- Return 1 if all locking failed ---------------------------------
+# === Return 1 if all locking failed =================================
 case "$count_success:$count_all" in
-  0:[!0]*) exit 1;;
-        *) exit 0;;
+  0:[!0]*) exit_trap 1;;
+        *) exit_trap 0;;
 esac
