utf8wc: Added the line mode

diff --git a/utf8wc b/utf8wc
--- a/utf8wc
+++ b/utf8wc
@@ -4,8 +4,16 @@
 #
 # UTF8WC - A Halfwidth Unit Ruler for Strings Contain UTF-8 Characters
 #
-# USAGE: utf8wc <file> [file ...]
-# RET  : stdout ... Length of the given string by halfwidth unit every
+# Usage  : utf8wc [-fl] <file> [file ...]
+# Options: -f ... Count text in every file (default)
+#                 * The output in this mode is the following.
+#                     <total length of the text data in the file>
+#                 * This option is exclusive with the "-l" option.
+#          -l ... Count text in every line
+#                 * The output in this mode is the following.
+#                     <length in the line> <original text string>
+#                 * This option is exclusive with the "-f" option.
+# Return : stdout ... Length of the given string by halfwidth unit every
 #                   file a line
 #
 # === Example ===
@@ -16,9 +24,14 @@
 #    > echo "ｱ"       | utf8wc
 # 3. This example returns 7.
 #    > echo "ﾐﾄﾞﾘ1号" | utf8wc
+# 4. This example returns 7.
+#    $ printf "あいうえお\nﾐﾄﾞﾘ1号\n" | utf8wc
+#    10 あいうえお
+#    7 ﾐﾄﾞﾘ1号
+#    $ 
 #
 #
-# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2020-05-06
+# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2023-11-10
 #
 # This is a public-domain software (CC0). It means that all of the
 # people can use this for any purposes with no restrictions at all.
@@ -46,8 +59,16 @@ export UNIX_STD=2003  # to make HP-UX conform to POSIX
 # === Define the functions for printing usage ========================
 print_usage_and_exit () {
   cat <<-USAGE 1>&2
-	Usage   : ${0##*/} <file> [file...]
-	Version : 2020-05-06 22:42:19 JST
+	Usage   : ${0##*/} [-l] <file> [file...]
+	Options : -f ... Count text in every file (default)
+	                 * The output in this mode is the following.
+	                     <total length of the text data in the file>
+	                 * This option is exclusive with the "-l" option.
+	          -l ... Count text in every line
+	                 * The output in this mode is the following.
+	                     <length in the line> <original text string>
+	                 * This option is exclusive with the "-f" option.
+	Version : 2023-11-10 16:02:47 JST
 	USAGE
   exit 1
 }
@@ -57,10 +78,66 @@ print_usage_and_exit () {
 # Argument Parsing
 ######################################################################
 
+# === Set default values =============================================
+mode='f'
+
 # === Print usage and exit if one of the help options is set =========
-case "$# ${1:-}" in
-  '1 -h'|'1 --help'|'1 --version') print_usage_and_exit;;
-esac
+optmode=''
+while :; do
+  case $# in 0) break;; esac
+  case "$optmode" in
+    '') case "$1" in
+          -)       case $# in 1) break;; esac
+                   ;;
+          -[fl]*)
+                     s=$(printf '%s\n' "${1#-}"                           |
+                         awk '{opt = "_"; err="";                         #
+                               l = length($0);                            #
+                               for (n=1;n<=l;n++) {                       #
+                                 c = substr($0, n, 1);                    #
+                                 if      (c=="f") { gsub(/fl/,"",opt);    #
+                                                    opt = opt "f";      } #
+                                 else if (c=="l") { gsub(/fl/,"",opt);    #
+                                                    opt = opt "l";      } #
+                                 else             { err = "!";          } #
+                               }                                          #
+                               arg = (n<l) ? substr($0,n+1) : "";         #
+                               printf("%s%s %s",err,opt,arg);           }')
+                     arg=${s#* }
+                     s=${s%% *}
+                     case "$s" in '!'*) print_usage_and_exit;; esac
+                     case "$s" in  *f*) mode='f'            ;; esac
+                     case "$s" in  *l*) mode='l'            ;; esac
+                     shift;
+                     case "$arg" in '') continue;; esac
+                     ;;
+          --file)    mode='f'
+                     shift
+                     continue
+                     ;;
+          --line)    mode='l'
+                     shift
+                     continue
+                     ;;
+          --)        shift
+                     break
+                     ;;
+          -*)        print_usage_and_exit
+                     ;;
+          *)         break
+                     ;;
+        esac
+        ;;
+    *)  arg=$1
+        shift
+        ;;
+  esac
+  case "$optmode" in
+   #X) optX=$arg                                       ;;
+    *) error_exit 1 'There is a BUG is in this program';;
+  esac
+  optmode=''
+done
 
 # === Set "-" into the 1st argument if no argument is given ==========
 case $# in 0) set -- -;; esac
@@ -69,6 +146,9 @@ case $# in 0) set -- -;; esac
 ######################################################################
 # Main
 ######################################################################
+
+# === whole text count mode ==========================================
+case $mode in 'f')
 
 ret=0
 for file in "$@"; do
@@ -134,13 +214,61 @@ for file in "$@"; do
          }
          return len;
        }' "$file" 2>/dev/null
-  case $? in
+  ret=$?
+  case $ret in
     0) : ;;
     *)
     echo "${0##*/}: Cannot open the file: $file" 1>&2
-    ret=1
   esac
 done
+
+# === ever line text count mode ======================================
+;; 'l') 
+
+ret=0
+for file in "$@"; do
+  awk '# counting
+       { print utf8strlen($0),$0; }
+
+       # strlen for UTF-8 (main)
+       function utf8strlen(str, len,i,l1,l2,l3) {
+         len = 0;
+         for (i = 1; i <= length(str); i++) {
+           len++;
+           l1=substr(str, i, 1);
+           if        (l1 =="\010") {len-=2;continue;
+           } else if (l1 < "\200") {       continue;
+           } else if (l1 < "\300") {len--; continue;
+           } else if (l1 < "\340") {i++;
+           } else if (l1 < "\360") {
+             if (l1 == "\357") {
+               l2 = substr(str, i+1, 1);
+               if (l2 == "\275") {
+                 l3 = substr(str, i+2, 1);
+                 if ((l3 >= "\240") && (l3 < "\300")) {len--;}
+               } else if (l2 == "\276") {
+                 l3 = substr(str, i+2, 1);
+                 if ((l3 >= "\200") && (l3 < "\240")) {len--;}
+               }
+             }
+             i += 2;
+           } else if (l1 < "\370") {i += 3;
+           } else if (l1 < "\374") {i += 4;
+           } else if (l1 < "\376") {i += 5;
+           } else                  {len-- ; continue;}
+           len++;
+         }
+         return len;
+       }' "$file" 2>/dev/null
+  ret=$?
+  case $ret in
+    0) : ;;
+    *)
+    echo "${0##*/}: Cannot open the file: $file" 1>&2
+  esac
+done
+
+;; esac
 
 
 ######################################################################
